'''
    visualize.py  –  Audio Beat & Frequency Visualizer

    Generates a rich, dark-themed multi-panel visualization of your audio file,
    showing exactly WHERE the detected beats are and WHY they were chosen.

    Panels:
        1. Waveform + all final beat markers
        2. Mel spectrogram (full frequency map over time)
        3. RMS energy envelope + energy-peak markers
        4. Spectral flux novelty curve + novelty-peak markers
        5. Frequency band breakdown (sub-bass, bass, mid, high)
        6. Beat density histogram (how busy different song sections are)

    Dependencies:
        pip install librosa numpy scipy matplotlib

    Usage:
        python visualize.py <audio_file> [--fps 24] [--min-gap 1.5]
                            [--target-count 60] [--sensitivity medium]
                            [--out-img visualization.png]
'''

import argparse
import librosa
import librosa.display
import numpy as np
import matplotlib
matplotlib.use('Agg')   # off-screen rendering, no display needed
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyArrowPatch
from scipy.signal import find_peaks
import warnings
warnings.filterwarnings('ignore')

# ── re-use detection helpers from detect_beats ────────────────────────────────

def get_beat_grid(y, sr):
    tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)
    tempo_val = float(tempo[0]) if hasattr(tempo, '__len__') else float(tempo)
    return librosa.frames_to_time(beat_frames, sr=sr), tempo_val


def get_energy_peaks(y, sr, min_gap=1.5):
    hop = 512
    rms = librosa.feature.rms(y=y, hop_length=hop)[0]
    window = max(3, int(sr / hop * 0.3))
    smoothed = np.convolve(rms, np.ones(window) / window, mode='same')
    min_distance = int(min_gap * sr / hop)
    threshold = np.percentile(smoothed, 60)
    peaks, _ = find_peaks(smoothed, height=threshold, distance=min_distance)
    return (
        librosa.frames_to_time(np.arange(len(smoothed)), sr=sr, hop_length=hop),
        smoothed,
        librosa.frames_to_time(peaks, sr=sr, hop_length=hop),
        rms
    )


def get_spectral_flux(y, sr, min_gap=1.5):
    hop = 512
    S = np.abs(librosa.stft(y, hop_length=hop))
    log_S = librosa.amplitude_to_db(S, ref=np.max)
    flux = np.maximum(0, np.diff(log_S, axis=1)).mean(axis=0)
    window = max(3, int(sr / hop * 0.2))
    flux_smooth = np.convolve(flux, np.ones(window) / window, mode='same')
    min_distance = int(min_gap * sr / hop)
    threshold = np.percentile(flux_smooth, 75)
    peaks, _ = find_peaks(flux_smooth, height=threshold, distance=min_distance)
    times = librosa.frames_to_time(np.arange(len(flux_smooth)), sr=sr, hop_length=hop)
    return times, flux_smooth, librosa.frames_to_time(peaks + 1, sr=sr, hop_length=hop)


def get_structural_boundaries(y, sr):
    hop = 512
    chroma = librosa.feature.chroma_cqt(y=y, sr=sr, hop_length=hop)
    bounds = librosa.segment.agglomerative(chroma, k=8)
    bound_times = librosa.frames_to_time(bounds, sr=sr, hop_length=hop)
    duration = len(y) / sr
    return [t for t in bound_times.tolist() if t > 0.5 and t < duration - 0.5]


def get_final_beats(beats_file):
    """Read the beats.txt already generated by detect_beats.py"""
    try:
        with open(beats_file, 'r') as f:
            return [float(line.strip()) for line in f if line.strip()]
    except FileNotFoundError:
        return []


def get_freq_bands(y, sr):
    """Split audio into frequency bands and compute their energy over time"""
    hop = 512
    S = np.abs(librosa.stft(y, hop_length=hop)) ** 2
    freqs = librosa.fft_frequencies(sr=sr)

    bands = {
        'Sub-bass\n(20-60 Hz)':    (20,   60),
        'Bass\n(60-250 Hz)':       (60,   250),
        'Mids\n(250-4k Hz)':       (250,  4000),
        'Highs\n(4k-20k Hz)':      (4000, 20000),
    }
    times = librosa.frames_to_time(np.arange(S.shape[1]), sr=sr, hop_length=hop)
    results = {}
    for name, (lo, hi) in bands.items():
        mask = (freqs >= lo) & (freqs <= hi)
        energy = S[mask, :].mean(axis=0) if mask.any() else np.zeros(S.shape[1])
        results[name] = energy
    return times, results


# ── Colour palette ─────────────────────────────────────────────────────────────

DARK_BG     = '#0d0d0d'
PANEL_BG    = '#141414'
GRID_COL    = '#222222'
WAVEFORM_C  = '#4fc3f7'   # cyan
ENERGY_C    = '#ff9800'   # amber
FLUX_C      = '#ab47bc'   # purple
BEAT_C      = '#ef5350'   # red  (final selected)
STRUCT_C    = '#66bb6a'   # green (section boundaries)
ENERGY_PK   = '#ffcc02'   # yellow peaks
FLUX_PK     = '#e040fb'   # magenta peaks

BAND_COLS = ['#e53935', '#fb8c00', '#43a047', '#1e88e5']   # red/orange/green/blue


# ── Main visualisation ─────────────────────────────────────────────────────────

def build_visualization(audio_file, beats_file, out_img, min_gap, target_count):

    print("\nLoading audio...")
    y, sr = librosa.load(audio_file)
    duration = len(y) / sr
    time_axis = np.linspace(0, duration, len(y))

    print("Extracting signals...")
    beat_grid, tempo = get_beat_grid(y, sr)
    e_times, e_smooth, e_peaks, rms_raw = get_energy_peaks(y, sr, min_gap)
    f_times, f_flux, f_peaks = get_spectral_flux(y, sr, min_gap)
    struct_bounds = get_structural_boundaries(y, sr)
    final_beats = get_final_beats(beats_file)
    band_times, bands = get_freq_bands(y, sr)

    hop = 512
    mel = librosa.feature.melspectrogram(y=y, sr=sr, hop_length=hop, n_mels=128, fmax=8000)
    mel_db = librosa.power_to_db(mel, ref=np.max)

    print("Building figure...")

    fig = plt.figure(figsize=(22, 24), facecolor=DARK_BG)
    fig.suptitle(
        f'Audio Beat & Frequency Analysis  ·  {audio_file.split("/")[-1].split(chr(92))[-1]}\n'
        f'Tempo: {tempo:.1f} BPM  ·  Duration: {duration:.1f}s  ·  '
        f'{len(final_beats)} transition markers selected',
        fontsize=15, color='white', fontweight='bold', y=0.99
    )

    gs = gridspec.GridSpec(6, 1, figure=fig,
                           hspace=0.55, top=0.96, bottom=0.04,
                           left=0.07, right=0.97)

    def style_ax(ax, title, ylabel=''):
        ax.set_facecolor(PANEL_BG)
        ax.tick_params(colors='#888888', labelsize=8)
        ax.set_title(title, color='#cccccc', fontsize=10, pad=6, loc='left', fontweight='bold')
        ax.set_ylabel(ylabel, color='#888888', fontsize=8)
        ax.set_xlim(0, duration)
        for spine in ax.spines.values():
            spine.set_edgecolor(GRID_COL)
        ax.grid(True, color=GRID_COL, linewidth=0.4, linestyle='--', alpha=0.7)

    def draw_beat_markers(ax, times, color, alpha=0.6, lw=1.2, label=''):
        for t in times:
            ax.axvline(x=t, color=color, alpha=alpha, linewidth=lw)
        if label:
            ax.plot([], [], color=color, alpha=alpha, linewidth=lw, label=label)

    # ── Panel 1: Waveform + final beats ─────────────────────────────────────
    ax1 = fig.add_subplot(gs[0])
    style_ax(ax1, '1.  Waveform  +  Final Transition Markers', 'Amplitude')
    ax1.plot(time_axis, y, color=WAVEFORM_C, linewidth=0.35, alpha=0.85)
    draw_beat_markers(ax1, final_beats, BEAT_C,    alpha=0.85, lw=1.5, label=f'Transitions ({len(final_beats)})')
    draw_beat_markers(ax1, struct_bounds, STRUCT_C, alpha=0.8,  lw=2.0, label=f'Section boundaries ({len(struct_bounds)})')
    ax1.legend(loc='upper right', fontsize=7.5, facecolor='#1a1a1a', edgecolor='#333', labelcolor='white')

    # ── Panel 2: Mel spectrogram ─────────────────────────────────────────────
    ax2 = fig.add_subplot(gs[1])
    style_ax(ax2, '2.  Mel Spectrogram  (full frequency content over time)', 'Frequency (Hz)')
    img = librosa.display.specshow(
        mel_db, sr=sr, hop_length=hop, x_axis='time', y_axis='mel',
        fmax=8000, ax=ax2, cmap='magma'
    )
    draw_beat_markers(ax2, final_beats,  BEAT_C,   alpha=0.5, lw=1.0)
    draw_beat_markers(ax2, struct_bounds, STRUCT_C, alpha=0.7, lw=1.8)
    cbar = fig.colorbar(img, ax=ax2, format='%+2.0f dB', pad=0.01)
    cbar.ax.yaxis.set_tick_params(color='#888')
    plt.setp(plt.getp(cbar.ax.axes, 'yticklabels'), color='#888', fontsize=7)

    # ── Panel 3: RMS energy ──────────────────────────────────────────────────
    ax3 = fig.add_subplot(gs[2])
    style_ax(ax3, '3.  RMS Energy Envelope  +  Energy Peaks', 'RMS')
    ax3.fill_between(e_times, e_smooth, color=ENERGY_C, alpha=0.25)
    ax3.plot(e_times, e_smooth, color=ENERGY_C, linewidth=0.8, alpha=0.9)
    ax3.scatter(e_peaks, [e_smooth[np.argmin(np.abs(e_times - t))] for t in e_peaks],
                color=ENERGY_PK, zorder=5, s=30, label=f'Energy peaks ({len(e_peaks)})')
    draw_beat_markers(ax3, final_beats, BEAT_C, alpha=0.4, lw=1.0)
    ax3.legend(loc='upper right', fontsize=7.5, facecolor='#1a1a1a', edgecolor='#333', labelcolor='white')

    # ── Panel 4: Spectral flux (novelty) ────────────────────────────────────
    ax4 = fig.add_subplot(gs[3])
    style_ax(ax4, '4.  Spectral Flux  (drops, builds, timbral changes)', 'Novelty')
    ax4.fill_between(f_times, f_flux, color=FLUX_C, alpha=0.25)
    ax4.plot(f_times, f_flux, color=FLUX_C, linewidth=0.8, alpha=0.9)
    ax4.scatter(f_peaks, [f_flux[np.argmin(np.abs(f_times - t))] for t in f_peaks],
                color=FLUX_PK, zorder=5, s=25, label=f'Novelty peaks ({len(f_peaks)})')
    draw_beat_markers(ax4, final_beats, BEAT_C, alpha=0.4, lw=1.0)
    ax4.legend(loc='upper right', fontsize=7.5, facecolor='#1a1a1a', edgecolor='#333', labelcolor='white')

    # ── Panel 5: Frequency band breakdown ───────────────────────────────────
    ax5 = fig.add_subplot(gs[4])
    style_ax(ax5, '5.  Frequency Band Energies  (sub-bass / bass / mids / highs)', 'Energy')
    for (name, energy), col in zip(bands.items(), BAND_COLS):
        norm = energy / (energy.max() + 1e-9)
        ax5.plot(band_times, norm, color=col, linewidth=0.8, alpha=0.85, label=name.replace('\n', ' '))
    draw_beat_markers(ax5, final_beats, BEAT_C, alpha=0.3, lw=0.8)
    ax5.legend(loc='upper right', fontsize=7.5, facecolor='#1a1a1a', edgecolor='#333',
               labelcolor='white', ncol=2)

    # ── Panel 6: Beat density histogram ─────────────────────────────────────
    ax6 = fig.add_subplot(gs[5])
    style_ax(ax6, '6.  Transition Density  (where in the song do cuts happen?)', 'Cuts per bin')
    ax6.set_facecolor(PANEL_BG)
    if final_beats:
        n_bins = max(20, int(duration / 5))
        counts, edges = np.histogram(final_beats, bins=n_bins, range=(0, duration))
        centers = (edges[:-1] + edges[1:]) / 2
        width = edges[1] - edges[0]
        bars = ax6.bar(centers, counts, width=width * 0.85, color=BEAT_C, alpha=0.75, edgecolor='none')
        # Colour the tallest bars brighter
        max_c = counts.max() if counts.max() > 0 else 1
        for bar, c in zip(bars, counts):
            bar.set_alpha(0.4 + 0.55 * (c / max_c))
    draw_beat_markers(ax6, struct_bounds, STRUCT_C, alpha=0.6, lw=2.0, label='Section boundary')
    ax6.legend(loc='upper right', fontsize=7.5, facecolor='#1a1a1a', edgecolor='#333', labelcolor='white')

    # ── Add shared time label ────────────────────────────────────────────────
    for ax in [ax1, ax2, ax3, ax4, ax5, ax6]:
        ax.set_xlabel('Time (seconds)', color='#888888', fontsize=7)

    print(f"Saving to {out_img}...")
    plt.savefig(out_img, dpi=150, bbox_inches='tight', facecolor=DARK_BG)
    plt.close()
    print(f"Saved! -> {out_img}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Audio Beat & Frequency Visualizer"
    )
    parser.add_argument("file", help="Path to audio file (mp3/wav)")
    parser.add_argument("--beats", default="output/beats.txt",
                        help="Path to the beats.txt output of detect_beats.py")
    parser.add_argument("--min-gap", type=float, default=1.5)
    parser.add_argument("--target-count", type=int, default=60)
    parser.add_argument("--out-img", default="output/visualization.png",
                        help="Output PNG path (default: output/visualization.png)")
    args = parser.parse_args()

    build_visualization(
        audio_file=args.file,
        beats_file=args.beats,
        out_img=args.out_img,
        min_gap=args.min_gap,
        target_count=args.target_count,
    )


if __name__ == "__main__":
    main()
